esbjKbh1.in "Middelfart"    "Odense"
esbjKbh1.in "Nyborg"        "Roskilde"
esbjKbh1.in "Esbjerg"       "Ringsted"
esbjKbh1.in "Esbjerg"       "København H"
esbjKbh2.in "København H"   "Esbjerg"
esbjKbh2.in "Bramming"      "Høje Taastrup"
esbjKbh2.in "Slagelse"      "Sorø"
esbjKbh2.in "Valby"         "Vejen"
all.in      "Frederikshavn" "Køge"
all.in      "Sindal"        "Brønderslev"
all.in      "Humlebæk"      "Østerport"
all.in      "Skodsborg"     "Solrød Strand"
all.in      "Hillerød"      "Vrå"
gitter.in   "a1"            "c3"
gitter.in   "a2"            "b1"
